import { useEffect, useMemo, useRef, useState } from 'react';
import type { FeedingSession, FeedingType, Settings, Side } from './types';
import { getSessions, getSettings, removeSession, saveSession, saveSettings } from './storage';
import { nextInterval } from './interval';

type Screen = 'home' | 'running' | 'summary' | 'settings';
const copy = {
  ko: { start: '수유 시작', stop: '수유 종료', breast: '모유', bottle: '분유', diaper: '기저귀 교체', today: '오늘', feedings: '회 수유', last: '마지막', ago: '전', next: '다음 수유 예정', progress: '수유 중', window: '다음 수유 창', summary: '오늘 수유 요약', total: '총 수유', duration: '총 시간', diapers: '기저귀', export: 'PDF 내보내기', settings: '설정', empty: '오늘 기록된 수유가 없습니다', undo: '실행 취소', saved: '수유 기록 저장됨', baby: '아기 이름', birth: '생년월일', close: '닫기', advice: '간격은 기록을 바탕으로 한 참고 정보이며 의학적 조언이 아닙니다.' },
  en: { start: 'START', stop: 'STOP', breast: 'Breast', bottle: 'Bottle', diaper: 'Diaper change', today: 'Today', feedings: 'feedings', last: 'Last', ago: 'ago', next: 'Next feeding in', progress: 'Feeding in progress', window: 'Next feeding window', summary: 'Today Summary', total: 'Total feedings', duration: 'Total time', diapers: 'Diapers', export: 'Export PDF', settings: 'Settings', empty: 'No feeding records today', undo: 'Undo', saved: 'Feeding saved', baby: "Baby's name", birth: 'Birth date', close: 'Close', advice: 'Timing guidance is based on your records and is not medical advice.' }
};
const dayStart = (n = Date.now()) => new Date(new Date(n).setHours(0, 0, 0, 0)).getTime();
const duration = (ms: number) => { const s = Math.max(0, Math.floor(ms / 1000)); return `${String(Math.floor(s / 3600)).padStart(2, '0')}:${String(Math.floor(s % 3600 / 60)).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`; };
const shortDuration = (ms: number) => { const m = Math.round(ms / 60000); return m >= 60 ? `${Math.floor(m / 60)}h ${m % 60}m` : `${m}m`; };
const clock = (n: number) => new Intl.DateTimeFormat('ko-KR', { hour: '2-digit', minute: '2-digit', hour12: false }).format(n);
const remaining = (ms: number) => { const m = Math.max(0, Math.ceil(ms / 60000)); return `${Math.floor(m / 60)}h ${m % 60}m`; };
const getAge = (date: string) => date ? Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 86400000)) : 0;

export default function App() {
  const [sessions, setSessions] = useState<FeedingSession[]>(getSessions);
  const [settings, setSettings] = useState<Settings>(getSettings);
  const [screen, setScreen] = useState<Screen>('home');
  const [type, setType] = useState<FeedingType>('breast'); const [side, setSide] = useState<Side>('left'); const [volume, setVolume] = useState<number | null>(60); const [diaper, setDiaper] = useState(false);
  const [active, setActive] = useState<FeedingSession | null>(null); const [now, setNow] = useState(Date.now()); const [toast, setToast] = useState<{ session: FeedingSession; until: number } | null>(null);
  const touchX = useRef<number | null>(null); const t = copy[settings.language];
  useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, []);
  useEffect(() => { if (toast && now > toast.until) setToast(null); }, [now, toast]);
  useEffect(() => { saveSettings(settings); document.documentElement.lang = settings.language; }, [settings]);
  const today = useMemo(() => sessions.filter(s => s.startTime >= dayStart()).sort((a,b) => b.startTime-a.startTime), [sessions]);
  const last = sessions[0]; const interval = nextInterval(last, getAge(settings.birthDate), sessions);
  const lastUsed: Side | null = sessions.find(s => s.feedingType === 'breast')?.breastSide || null;
  const start = () => { navigator.vibrate?.(10); const time = Date.now(); setActive({ id: crypto.randomUUID(), startTime: time, endTime: null, durationMs: 0, feedingType: type, breastSide: type === 'breast' ? side : null, volumeMl: type === 'bottle' ? volume : null, diaperChanged: diaper, notes: '', createdAt: time }); setScreen('running'); };
  const stop = () => { if (!active) return; navigator.vibrate?.(10); const finished = { ...active, endTime: Date.now(), durationMs: Date.now() - active.startTime }; setSessions(saveSession(finished)); setActive(null); setDiaper(false); setToast({ session: finished, until: Date.now() + 5000 }); setScreen('home'); };
  const undo = () => { if (!toast) return; removeSession(toast.session.id); setSessions(getSessions()); setToast(null); };
  const exportPdf = async () => { const { jsPDF } = await import('jspdf'); const doc = new jsPDF(); doc.setFontSize(20); doc.text('FILT Feeding Report', 20, 20); doc.setFontSize(11); doc.text(`${settings.babyName || 'Baby'} · ${new Date().toLocaleDateString()}`, 20, 30); doc.text(`Total: ${today.length} feeds · ${shortDuration(today.reduce((a,s) => a+s.durationMs,0))}`, 20, 38); today.slice().reverse().forEach((s, i) => doc.text(`${clock(s.startTime)}  ${labelFor(s)}  ${shortDuration(s.durationMs)}${s.diaperChanged ? '  + diaper' : ''}`, 20, 52 + i * 8)); doc.save(`filt-feeding-report-${new Date().toISOString().slice(0,10)}.pdf`); };
  const navigate = (e: React.TouchEvent) => { if (touchX.current === null) return; const d = e.changedTouches[0].clientX - touchX.current; if (Math.abs(d) > 70) { if (screen === 'home' && d < 0) setScreen('summary'); if (screen === 'summary' && d > 0) setScreen('home'); } touchX.current = null; };
  return <main className="app" onTouchStart={e => { touchX.current = e.touches[0].clientX; }} onTouchEnd={navigate}>
    <header><div className="brand"><b>FILT</b><span>NEWBORN FEEDING</span></div><button className="language" onClick={() => setSettings({...settings, language: settings.language === 'ko' ? 'en' : 'ko'})}><b className={settings.language === 'ko' ? 'activeLang' : ''}>KO</b><i>|</i><b className={settings.language === 'en' ? 'activeLang' : ''}>EN</b></button></header>
    {screen === 'home' && <Home t={t} today={today} last={last} interval={interval.ms} type={type} setType={setType} side={side} setSide={setSide} lastUsed={lastUsed} volume={volume} setVolume={setVolume} diaper={diaper} setDiaper={setDiaper} start={start} openSettings={() => setScreen('settings')} />}
    {screen === 'running' && active && <Running t={t} active={active} now={now} interval={interval.ms} stop={stop} />}
    {screen === 'summary' && <Summary t={t} today={today} exportPdf={exportPdf} openSettings={() => setScreen('settings')} />}
    {screen === 'settings' && <SettingsView t={t} settings={settings} update={setSettings} close={() => setScreen('home')} />}
    {toast && <div className="toast"><span>✓ {t.saved}</span><button onClick={undo}>{t.undo}</button></div>}
  </main>;
}

function Home({t,today,last,interval,type,setType,side,setSide,lastUsed,volume,setVolume,diaper,setDiaper,start,openSettings}: any) { const since = last ? remaining(Date.now()-last.startTime) : '—'; return <section className="screen home"><div className="status"><span>{t.today}: <b>{today.length}{t.feedings}</b></span><span>{t.last}: {last ? `${since} ${t.ago || ''}` : '—'}</span></div><div className="card"><div className="mode"><button className={type==='breast'?'selected':''} onClick={()=>setType('breast')}>{t.breast}</button><button className={type==='bottle'?'selected':''} onClick={()=>setType('bottle')}>{t.bottle}</button></div>{type==='breast'?<div className="sides"><button className={side==='left'?'selected':''} onClick={()=>setSide('left')}>◀ {t.left}<small>{lastUsed==='left'?'•':''}</small></button><button className={side==='right'?'selected':''} onClick={()=>setSide('right')}>{t.right} ▶<small>{lastUsed==='right'?'•':''}</small></button></div>:<div className="volume"><label>🍼</label><input type="number" min="0" max="500" step="5" value={volume ?? ''} onChange={e=>setVolume(e.target.value ? Number(e.target.value) : null)} /><span>ml</span><div className="presets">{[30,60,90,120].map(n=><button key={n} className={volume===n?'selected':''} onClick={()=>setVolume(volume===n?null:n)}>{n}ml</button>)}</div></div>}<button className="big start" onClick={start}>▶ <span>{t.start}</span></button><label className="check"><input type="checkbox" checked={diaper} onChange={e=>setDiaper(e.target.checked)}/><span>{t.diaper}</span></label></div><footer><span className="interval"><em/> ⏱ {t.next}: <b>{last ? remaining(interval-(Date.now()-last.startTime)) : '1h 45m'}</b></span><button onClick={openSettings}>⚙</button></footer></section>; }
function Running({t,active,now,interval,stop}: any) { return <section className="screen running"><div className="runningBox"><p>{t.progress}</p><div className="elapsed">{duration(now-active.startTime)}</div><div className="window"><em/> ⏱ {t.window}: {remaining(interval-(now-active.startTime))}</div><button className="big stop" onClick={stop}>■ <span>{t.stop}</span></button><small>{labelFor(active)}{active.volumeMl ? ` · ${active.volumeMl}ml` : ''}</small></div></section>; }
function Summary({t,today,exportPdf,openSettings}: any) { const total = today.reduce((a: number,s: FeedingSession)=>a+s.durationMs,0); const diaper = today.filter((s: FeedingSession)=>s.diaperChanged).length; const max = Math.max(...today.map((s: FeedingSession)=>s.durationMs),1); return <section className="screen summary"><div className="summaryHead"><h1>{t.summary}</h1><span>{new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',weekday:'short'}).format(new Date())}</span></div><div className="stats"><Pill value={today.length} label={t.total}/><Pill value={shortDuration(total)} label={t.duration}/><Pill value={diaper} label={t.diapers}/></div>{today.length?<div className="timeline">{today.slice().reverse().map((s: FeedingSession)=><div className="session" key={s.id}><time>{clock(s.startTime)}</time><div className="bar"><i style={{width:`${Math.max(12,s.durationMs/max*100)}%`}}/></div><b>{labelFor(s)} · {s.feedingType==='bottle'?`${s.volumeMl||0}ml`:shortDuration(s.durationMs)}</b></div>)}</div>:<div className="empty"><span>◌</span><p>{t.empty}</p></div>}<div className="summaryActions"><button onClick={exportPdf}>📄 {t.export}</button><button onClick={openSettings}>⚙ {t.settings}</button></div></section>; }
function Pill({value,label}: any) { return <div className="pill"><strong>{value}</strong><span>{label}</span></div>; }
function SettingsView({t,settings,update,close}: any) { return <section className="screen settings"><div className="summaryHead"><h1>{t.settings}</h1><button onClick={close}>×</button></div><label>{t.baby}<input value={settings.babyName} onChange={e=>update({...settings,babyName:e.target.value})} placeholder=""/></label><label>{t.birth}<input type="date" value={settings.birthDate} onChange={e=>update({...settings,birthDate:e.target.value})}/></label><p>{t.advice}</p><button className="big start" onClick={close}>{t.close}</button></section>; }
function labelFor(s: FeedingSession) { return s.feedingType === 'bottle' ? 'Btl' : s.breastSide === 'left' ? 'L' : 'R'; }
